[package]
name = "rgb-ivy"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {version= "1.40.0", features = ["rt-multi-thread"]}
axum = "0.7.6"
tracing-subscriber = "0.3.18"
serde ={version= "1.0.210",features = ["derive"]}
serde_json = "1.0.128"